name: Build Docker image

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npx gulp docker-build
        docker save -o ${{steps.package-name.outputs.packageName}}.tar ${{steps.package-name.outputs.imageName}} 
        
    - uses: actions/upload-artifact@v4
      with:
        name: docker
        path: ${{steps.package-name.outputs.packageName}}.tar