name: Load Artifacts from NPM

runs:
  using: composite
  steps:
    - id: detect-package-metadata
      uses: DevExpress/testcafe-build-system/actions/detect-package-metadata@main
    
    - uses: actions/download-artifact@v3
      with:
        name: npm

    - shell: bash
      run: tar --strip-components=1 -xzf '${{ format('.builds/{0}-{1}.tgz', steps.detect-package-metadata.outputs.name, steps.detect-package-metadata.outputs.version) }}'

    - uses: actions/github-script@v6
      with:
        script: |
          const workspaces = JSON.parse(${{ toJSON(steps.detect-package-metadata.outputs.workspaces) }});

          for (const workspace of workspaces)
            await exec.exec(`tar --strip-components=1 -C ${workspace.path} -xzf .builds/${workspace.name.replace(/\//g, '-')}-${workspace.version}.tgz`)

