name: Save matrix status

inputs:
  job-id:
    required: true

runs:
  using: composite
  steps:
    - name: Save status
      shell: bash
      run: echo ${{ job.status }} > matrix-status-${{ inputs.job-id }}.txt

    - uses: actions/upload-artifact@v4
      with:
        name: matrix-status
        path: matrix-status-${{ inputs.job-id }}.txt