name: Read matrix status

outputs:
  status: 
    description: "Matrix status (success|failure)"
    value: ${{ steps.matrix-status.outputs.status }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: matrix-status-*
        merge-multiple: true

    - name: Read matrix status
      id: matrix-status
      shell: bash
      run: echo status=$([ $(grep -h -v "success" matrix-status-*.txt | wc -l) -eq 0 ] && echo "success" || echo "failure") >> "$GITHUB_OUTPUT"

    - name: Remove files with statuses
      shell: bash
      run: rm matrix-status-*.txt