group:
  repos: |
    DevExpress/acorn-hammerhead
    DevExpress/angular-testcafe
    DevExpress/bin-v8-flags-filter
    DevExpress/callsite-record
    DevExpress/device-specs
    DevExpress/eslint-plugin-hammerhead
    DevExpress/esotope-hammerhead
    DevExpress/generator-testcafe-browser-provider
    DevExpress/generator-testcafe-reporter
    DevExpress/gulp-ll-next
    DevExpress/gulp-mocha-simple
    DevExpress/gulp-step
    DevExpress/hammerhead-health-monitor
    DevExpress/is-jquery-obj
    DevExpress/linux-platform-info
    DevExpress/log-update-async-hook
    DevExpress/match-url-wildcard
    DevExpress/mocha-reporter-spec-with-retries
    DevExpress/moment-duration-format-commonjs
    DevExpress/npm-auditor
    DevExpress/saucelabs-connector
    DevExpress/sauce-tunnel
    DevExpress/testcafe
    DevExpress/testcafe.io
    DevExpress/testcafe-browser-provider-browserstack
    DevExpress/testcafe-browser-provider-electron
    DevExpress/testcafe-browser-provider-saucelabs
    DevExpress/testcafe-browser-tools
    DevExpress/testcafe-example-multiuser-scenario
    DevExpress/testcafe-example-running-tests-using-saucectl
    DevExpress/testcafe-example-running-tests-using-travis-and-saucelabs
    DevExpress/testcafe-examples
    DevExpress/testcafe-hammerhead
    DevExpress/testcafeio-examples
    DevExpress/testcafe-legacy-api
    DevExpress/testcafe-react-selectors
    DevExpress/testcafe-reporter-json
    DevExpress/testcafe-reporter-list
    DevExpress/testcafe-reporter-minimal
    DevExpress/testcafe-reporter-nunit
    DevExpress/testcafe-reporter-spec
    DevExpress/testcafe-reporter-xunit
    DevExpress/testcafe-selector-generator
    DevExpress/testcafe-studio
  files:
    - source: workflows/
      dest: .github/workflows/
    - source: configs/labels.yml
      dest: .github/labels.yml
