name: Publish with publish-please

inputs:
  registry:
    required: false
  protocol:
    required: false
  token:
    required: false
  owner:
    required: false
  node-version:
    required: false
    default: 18
    
runs:
  using: composite
  steps:
    - uses: DevExpress/testcafe-build-system/actions/prepare@main
      with:
        node-version: ${{ inputs.node-version }}

    - uses: DevExpress/testcafe-build-system/actions/build@main

    - uses: DevExpress/testcafe-build-system/actions/login-npm@main
      with:
        registry: ${{ inputs.registry }}
        protocol: ${{ inputs.protocol }}
        token: ${{ inputs.token }}

    # TODO: do something with "npm install" changing package-lock.json
    - shell: bash
      run: git checkout -- package-lock.json || true

    - shell: bash
      run: npx @testcafe/publish-please || (git status && false)
